### ISSUE TITLE
Error with a module 

### ISSUE THREAD

**Issue by LorealEndPoint** [almenscorner/Munki-Manifest-Generator#6]
Hello, 

after an update of the version on Azure Automation it seems that there is a call of a module that does not work. 
here is the error on the Runbook. 

Traceback (most recent call last): File "/usr/src/tmp/8a7f0eb2-4efc-470f-bf33-b3ca382f769e/runbooks/MunkiManifest1.py", line 2, in <module> from munki_manifest_generator import main as mmg File "C:\userenv\lib\site-packages\munki_manifest_generator\main.py", line 17, in <module> from munki_manifest_generator.graph.make_api_request import make_api_request File "C:\userenv\lib\site-packages\munki_manifest_generator\graph\make_api_request.py", line 10, in <module> from retrying import retry ModuleNotFoundError: No module named 'retrying'

**Comment by almenscorner** [comment]
You need to import the python package to your Automation account: https://pypi.org/project/retrying/

**Comment by LorealEndPoint** [comment]
Thanks for your prompt answer. by adding the pkg it is working. i've another error but will find it. 
could be interesting to add that pkg in your doc as mandatory
